# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jcleng/desktop/work/lvgl_test_xmake/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jcleng/desktop/work/lvgl_test_xmake/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jcleng/desktop/work/lvgl_test_xmake/src/CMakeFiles /home/jcleng/desktop/work/lvgl_test_xmake/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jcleng/desktop/work/lvgl_test_xmake/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lvgl_fb

# Build rule for target.
lvgl_fb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lvgl_fb
.PHONY : lvgl_fb

# fast build rule for target.
lvgl_fb/fast:
	$(MAKE) -f CMakeFiles/lvgl_fb.dir/build.make CMakeFiles/lvgl_fb.dir/build
.PHONY : lvgl_fb/fast

#=============================================================================
# Target rules for targets named lvgl_demos

# Build rule for target.
lvgl_demos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lvgl_demos
.PHONY : lvgl_demos

# fast build rule for target.
lvgl_demos/fast:
	$(MAKE) -f lvgl/CMakeFiles/lvgl_demos.dir/build.make lvgl/CMakeFiles/lvgl_demos.dir/build
.PHONY : lvgl_demos/fast

#=============================================================================
# Target rules for targets named lvgl_examples

# Build rule for target.
lvgl_examples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lvgl_examples
.PHONY : lvgl_examples

# fast build rule for target.
lvgl_examples/fast:
	$(MAKE) -f lvgl/CMakeFiles/lvgl_examples.dir/build.make lvgl/CMakeFiles/lvgl_examples.dir/build
.PHONY : lvgl_examples/fast

#=============================================================================
# Target rules for targets named lvgl

# Build rule for target.
lvgl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lvgl
.PHONY : lvgl

# fast build rule for target.
lvgl/fast:
	$(MAKE) -f lvgl/CMakeFiles/lvgl.dir/build.make lvgl/CMakeFiles/lvgl.dir/build
.PHONY : lvgl/fast

#=============================================================================
# Target rules for targets named lv_drivers

# Build rule for target.
lv_drivers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lv_drivers
.PHONY : lv_drivers

# fast build rule for target.
lv_drivers/fast:
	$(MAKE) -f lv_drivers/CMakeFiles/lv_drivers.dir/build.make lv_drivers/CMakeFiles/lv_drivers.dir/build
.PHONY : lv_drivers/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/lvgl_fb.dir/build.make CMakeFiles/lvgl_fb.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/lvgl_fb.dir/build.make CMakeFiles/lvgl_fb.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/lvgl_fb.dir/build.make CMakeFiles/lvgl_fb.dir/main.c.s
.PHONY : main.c.s

mouse_cursor_icon.o: mouse_cursor_icon.c.o

.PHONY : mouse_cursor_icon.o

# target to build an object file
mouse_cursor_icon.c.o:
	$(MAKE) -f CMakeFiles/lvgl_fb.dir/build.make CMakeFiles/lvgl_fb.dir/mouse_cursor_icon.c.o
.PHONY : mouse_cursor_icon.c.o

mouse_cursor_icon.i: mouse_cursor_icon.c.i

.PHONY : mouse_cursor_icon.i

# target to preprocess a source file
mouse_cursor_icon.c.i:
	$(MAKE) -f CMakeFiles/lvgl_fb.dir/build.make CMakeFiles/lvgl_fb.dir/mouse_cursor_icon.c.i
.PHONY : mouse_cursor_icon.c.i

mouse_cursor_icon.s: mouse_cursor_icon.c.s

.PHONY : mouse_cursor_icon.s

# target to generate assembly for a file
mouse_cursor_icon.c.s:
	$(MAKE) -f CMakeFiles/lvgl_fb.dir/build.make CMakeFiles/lvgl_fb.dir/mouse_cursor_icon.c.s
.PHONY : mouse_cursor_icon.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lvgl_fb"
	@echo "... lvgl_demos"
	@echo "... lvgl_examples"
	@echo "... lvgl"
	@echo "... lv_drivers"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mouse_cursor_icon.o"
	@echo "... mouse_cursor_icon.i"
	@echo "... mouse_cursor_icon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

